/* Generated by Pyrex 0.9.5.1a on Sat Feb 24 16:41:32 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static PyObject *__Pyx_GetExcValue(void); /*proto*/

static void __Pyx_ReRaise(void); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from _once */


struct __pyx_obj_5_once_bindingLock {
  PyObject_HEAD
  int id;
};


struct __pyx_obj_5_once_BaseDescriptor {
  PyObject_HEAD
  PyObject *attrName;
  int isVolatile;
};

static PyTypeObject *__pyx_ptype_5_once_bindingLock = 0;
static PyTypeObject *__pyx_ptype_5_once_BaseDescriptor = 0;
static void (*__pyx_v_5_once__lockType);
static PyObject *__pyx_v_5_once_Py_None;
__PYX_EXTERN_C PyObject *(GET_DICTIONARY(PyObject *)); /*proto*/
__PYX_EXTERN_C long (_get_py_thread_ident(void)); /*proto*/
static int (__pyx_f_5_once_isLock(void (*))); /*proto*/
static int (__pyx_f_5_once_isOurs(void (*))); /*proto*/


/* Implementation of _once */


static PyObject *__pyx_n___all__;
static PyObject *__pyx_n_BaseDescriptor;

static int __pyx_f_5_once_11bindingLock___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5_once_11bindingLock___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":20 */
  ((struct __pyx_obj_5_once_bindingLock *)__pyx_v_self)->id = _get_py_thread_ident();

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_5_once_isLock(void (*__pyx_v_obj)) {
  int __pyx_r;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":28 */
  __pyx_r = (((struct _object (*))__pyx_v_obj)->ob_type == __pyx_v_5_once__lockType);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static int __pyx_f_5_once_isOurs(void (*__pyx_v_obj)) {
  int __pyx_v_id;
  struct __pyx_obj_5_once_bindingLock *__pyx_v_lock;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_v_lock = ((struct __pyx_obj_5_once_bindingLock *)Py_None); Py_INCREF(Py_None);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":34 */
  __pyx_v_id = _get_py_thread_ident();

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":35 */
  __pyx_1 = (PyObject *)__pyx_v_obj;
  Py_INCREF(__pyx_1);
  Py_DECREF(((PyObject *)__pyx_v_lock));
  __pyx_v_lock = ((struct __pyx_obj_5_once_bindingLock *)__pyx_1);
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":36 */
  __pyx_r = (__pyx_v_lock->id == __pyx_v_id);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_lock);
  return __pyx_r;
}

static PyObject *__pyx_n_onSet;

static int __pyx_f_5_once_14BaseDescriptor___set__(PyObject *__pyx_v_self, PyObject *__pyx_v_obj, PyObject *__pyx_v_value); /*proto*/
static int __pyx_f_5_once_14BaseDescriptor___set__(PyObject *__pyx_v_self, PyObject *__pyx_v_obj, PyObject *__pyx_v_value) {
  PyObject *__pyx_v_d;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  Py_INCREF(__pyx_v_value);
  __pyx_v_d = Py_None; Py_INCREF(Py_None);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":51 */
  __pyx_1 = GET_DICTIONARY(__pyx_v_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":52 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_onSet); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  Py_INCREF(__pyx_v_obj);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_obj);
  Py_INCREF(((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName);
  PyTuple_SET_ITEM(__pyx_2, 1, ((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName);
  Py_INCREF(__pyx_v_value);
  PyTuple_SET_ITEM(__pyx_2, 2, __pyx_v_value);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetItem(__pyx_v_d, ((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_once.BaseDescriptor.__set__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  Py_DECREF(__pyx_v_value);
  return __pyx_r;
}

static int __pyx_f_5_once_14BaseDescriptor___delete__(PyObject *__pyx_v_self, PyObject *__pyx_v_obj); /*proto*/
static int __pyx_f_5_once_14BaseDescriptor___delete__(PyObject *__pyx_v_self, PyObject *__pyx_v_obj) {
  PyObject *__pyx_v_d;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  __pyx_v_d = Py_None; Py_INCREF(Py_None);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":55 */
  __pyx_1 = GET_DICTIONARY(__pyx_v_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":56 */
  if (PyObject_DelItem(__pyx_v_d, ((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_once.BaseDescriptor.__delete__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  return __pyx_r;
}

static PyObject *__pyx_f_5_once_14BaseDescriptor_onSet(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5_once_14BaseDescriptor_onSet(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_obj = 0;
  PyObject *__pyx_v_attrName = 0;
  PyObject *__pyx_v_value = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"obj","attrName","value",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_obj, &__pyx_v_attrName, &__pyx_v_value)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  Py_INCREF(__pyx_v_attrName);
  Py_INCREF(__pyx_v_value);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":59 */
  Py_INCREF(__pyx_v_value);
  __pyx_r = __pyx_v_value;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  Py_DECREF(__pyx_v_attrName);
  Py_DECREF(__pyx_v_value);
  return __pyx_r;
}

static PyObject *__pyx_f_5_once_14BaseDescriptor_ofClass(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5_once_14BaseDescriptor_ofClass(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_attrName = 0;
  PyObject *__pyx_v_klass = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"attrName","klass",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_attrName, &__pyx_v_klass)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_attrName);
  Py_INCREF(__pyx_v_klass);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":62 */
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_attrName);
  Py_DECREF(__pyx_v_klass);
  return __pyx_r;
}

static PyObject *__pyx_n_ofClass;
static PyObject *__pyx_n_usageError;
static PyObject *__pyx_n_AttributeError;
static PyObject *__pyx_n_computeValue;

static PyObject *__pyx_k2p;

static char (__pyx_k2[]) = "Recursive attempt to compute attribute";

static PyObject *__pyx_f_5_once_14BaseDescriptor___get__(PyObject *__pyx_v_self, PyObject *__pyx_v_ob, PyObject *__pyx_v_typ); /*proto*/
static PyObject *__pyx_f_5_once_14BaseDescriptor___get__(PyObject *__pyx_v_self, PyObject *__pyx_v_ob, PyObject *__pyx_v_typ) {
  void (*__pyx_v_obj);
  PyObject *__pyx_v_n;
  PyObject *__pyx_v_d;
  PyObject *__pyx_v_value;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_ob);
  Py_INCREF(__pyx_v_typ);
  __pyx_v_n = Py_None; Py_INCREF(Py_None);
  __pyx_v_d = Py_None; Py_INCREF(Py_None);
  __pyx_v_value = Py_None; Py_INCREF(Py_None);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":73 */
  __pyx_1 = __pyx_v_ob == __pyx_v_5_once_Py_None;
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":74 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_ofClass); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    Py_INCREF(((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName);
    PyTuple_SET_ITEM(__pyx_3, 0, ((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName);
    Py_INCREF(__pyx_v_typ);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_typ);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_r = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":76 */
  Py_INCREF(((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName);
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = ((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->attrName;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":77 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_n); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_5 = (!__pyx_1);
  if (__pyx_5) {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":78 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_usageError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":80 */
  __pyx_4 = GET_DICTIONARY(__pyx_v_ob); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_4;
  __pyx_4 = 0;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":81 */
  __pyx_v_obj = PyDict_GetItem(__pyx_v_d,__pyx_v_n);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":83 */
  __pyx_1 = (__pyx_v_obj != 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":85 */
    __pyx_5 = (((struct _object (*))__pyx_v_obj)->ob_type == __pyx_v_5_once__lockType);
    if (__pyx_5) {

      /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":87 */
      __pyx_1 = __pyx_f_5_once_isOurs(__pyx_v_obj);
      if (__pyx_1) {

        /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":88 */
        __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        Py_INCREF(__pyx_k2p);
        PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k2p);
        Py_INCREF(__pyx_v_n);
        PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_n);
        __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        __Pyx_Raise(__pyx_4, 0, 0);
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
        goto __pyx_L6;
      }
      __pyx_L6:;
      goto __pyx_L5;
    }
    /*else*/ {

      /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":93 */
      __pyx_2 = (PyObject *)__pyx_v_obj;
      Py_INCREF(__pyx_2);
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L0;
    }
    __pyx_L5:;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":97 */
    __pyx_3 = PyObject_CallObject(((PyObject*)__pyx_ptype_5_once_bindingLock), 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_d, __pyx_v_n, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  __pyx_L4:;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":99 */
  /*try:*/ {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":100 */
    __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n_computeValue); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L7;}
    __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L7;}
    Py_INCREF(__pyx_v_ob);
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_ob);
    Py_INCREF(__pyx_v_d);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_d);
    Py_INCREF(__pyx_v_n);
    PyTuple_SET_ITEM(__pyx_2, 2, __pyx_v_n);
    __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L7;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_3;
    __pyx_3 = 0;

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":101 */
    __pyx_5 = (!((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->isVolatile);
    if (__pyx_5) {

      /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":102 */
      __pyx_4 = PyObject_GetAttr(__pyx_v_self, __pyx_n_onSet); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L7;}
      __pyx_2 = PyTuple_New(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L7;}
      Py_INCREF(__pyx_v_ob);
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_ob);
      Py_INCREF(__pyx_v_n);
      PyTuple_SET_ITEM(__pyx_2, 1, __pyx_v_n);
      Py_INCREF(__pyx_v_value);
      PyTuple_SET_ITEM(__pyx_2, 2, __pyx_v_value);
      __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L7;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_v_value);
      __pyx_v_value = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L9;
    }
    __pyx_L9:;
  }
  goto __pyx_L8;
  __pyx_L7:;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":104 */
  /*except:*/ {
    __Pyx_AddTraceback("_once.__get__");
    __pyx_4 = __Pyx_GetExcValue(); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":109 */
    __pyx_v_obj = PyDict_GetItem(__pyx_v_d,__pyx_v_n);

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":110 */
    __pyx_1 = (__pyx_v_obj != 0);
    if (__pyx_1) {
      __pyx_1 = __pyx_f_5_once_isLock(__pyx_v_obj);
      if (__pyx_1) {
        __pyx_1 = __pyx_f_5_once_isOurs(__pyx_v_obj);
      }
    }
    if (__pyx_1) {

      /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":111 */
      if (PyObject_DelItem(__pyx_v_d, __pyx_v_n) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
      goto __pyx_L10;
    }
    __pyx_L10:;

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":112 */
    __Pyx_ReRaise();
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    goto __pyx_L8;
  }
  __pyx_L8:;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":114 */
  __pyx_5 = ((struct __pyx_obj_5_once_BaseDescriptor *)__pyx_v_self)->isVolatile;
  if (__pyx_5) {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":115 */
    if (PyObject_DelItem(__pyx_v_d, __pyx_v_n) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
    goto __pyx_L11;
  }
  /*else*/ {

    /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":117 */
    if (PyObject_SetItem(__pyx_v_d, __pyx_v_n, __pyx_v_value) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  }
  __pyx_L11:;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":119 */
  Py_INCREF(__pyx_v_value);
  __pyx_r = __pyx_v_value;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_once.BaseDescriptor.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_ob);
  Py_DECREF(__pyx_v_typ);
  return __pyx_r;
}

static PyObject *__pyx_n_TypeError;

static PyObject *__pyx_k3p;

static char (__pyx_k3[]) = "%s was used in a type which does not support active bindings, but a valid attribute name was not supplied";

static PyObject *__pyx_f_5_once_14BaseDescriptor_usageError(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5_once_14BaseDescriptor_usageError(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":125 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_TypeError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_k3p, __pyx_v_self); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __Pyx_Raise(__pyx_2, 0, 0);
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_once.BaseDescriptor.usageError");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_5_once_14BaseDescriptor_computeValue(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5_once_14BaseDescriptor_computeValue(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_ob = 0;
  PyObject *__pyx_v_idict = 0;
  PyObject *__pyx_v_attrName = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"ob","idict","attrName",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_ob, &__pyx_v_idict, &__pyx_v_attrName)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_ob);
  Py_INCREF(__pyx_v_idict);
  Py_INCREF(__pyx_v_attrName);

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":133 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __Pyx_Raise(__pyx_1, __pyx_v_attrName, 0);
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_once.BaseDescriptor.computeValue");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_ob);
  Py_DECREF(__pyx_v_idict);
  Py_DECREF(__pyx_v_attrName);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_AttributeError, "AttributeError"},
  {&__pyx_n_BaseDescriptor, "BaseDescriptor"},
  {&__pyx_n_TypeError, "TypeError"},
  {&__pyx_n___all__, "__all__"},
  {&__pyx_n_computeValue, "computeValue"},
  {&__pyx_n_ofClass, "ofClass"},
  {&__pyx_n_onSet, "onSet"},
  {&__pyx_n_usageError, "usageError"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_5_once_bindingLock(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (__pyx_f_5_once_11bindingLock___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_5_once_bindingLock(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5_once_bindingLock(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_5_once_bindingLock(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_5_once_bindingLock[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_bindingLock = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_bindingLock = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_bindingLock = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_bindingLock = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_5_once_bindingLock = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_once.bindingLock", /*tp_name*/
  sizeof(struct __pyx_obj_5_once_bindingLock), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5_once_bindingLock, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_bindingLock, /*tp_as_number*/
  &__pyx_tp_as_sequence_bindingLock, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_bindingLock, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_bindingLock, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_5_once_bindingLock, /*tp_traverse*/
  __pyx_tp_clear_5_once_bindingLock, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5_once_bindingLock, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5_once_bindingLock, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_5_once_BaseDescriptor(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5_once_BaseDescriptor *p = (struct __pyx_obj_5_once_BaseDescriptor *)o;
  p->attrName = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_5_once_BaseDescriptor(PyObject *o) {
  struct __pyx_obj_5_once_BaseDescriptor *p = (struct __pyx_obj_5_once_BaseDescriptor *)o;
  Py_XDECREF(p->attrName);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5_once_BaseDescriptor(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5_once_BaseDescriptor *p = (struct __pyx_obj_5_once_BaseDescriptor *)o;
  if (p->attrName) {
    e = (*v)(p->attrName, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_5_once_BaseDescriptor(PyObject *o) {
  struct __pyx_obj_5_once_BaseDescriptor *p = (struct __pyx_obj_5_once_BaseDescriptor *)o;
  Py_XDECREF(p->attrName);
  p->attrName = Py_None; Py_INCREF(Py_None);
  return 0;
}

static PyObject *__pyx_tp_descr_get_5_once_BaseDescriptor(PyObject *o, PyObject *i, PyObject *c) {
  PyObject *r = 0;
  if (!i) i = Py_None;
  if (!c) c = Py_None;
  r = __pyx_f_5_once_14BaseDescriptor___get__(o, i, c);
  return r;
}

static int __pyx_tp_descr_set_5_once_BaseDescriptor(PyObject *o, PyObject *i, PyObject *v) {
  if (v) {
    return __pyx_f_5_once_14BaseDescriptor___set__(o, i, v);
  }
  else {
    return __pyx_f_5_once_14BaseDescriptor___delete__(o, i);
  }
}

static struct PyMethodDef __pyx_methods_5_once_BaseDescriptor[] = {
  {"onSet", (PyCFunction)__pyx_f_5_once_14BaseDescriptor_onSet, METH_VARARGS|METH_KEYWORDS, 0},
  {"ofClass", (PyCFunction)__pyx_f_5_once_14BaseDescriptor_ofClass, METH_VARARGS|METH_KEYWORDS, 0},
  {"usageError", (PyCFunction)__pyx_f_5_once_14BaseDescriptor_usageError, METH_VARARGS|METH_KEYWORDS, 0},
  {"computeValue", (PyCFunction)__pyx_f_5_once_14BaseDescriptor_computeValue, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_5_once_BaseDescriptor[] = {
  {"attrName", T_OBJECT, offsetof(struct __pyx_obj_5_once_BaseDescriptor, attrName), 0, 0},
  {"isVolatile", T_INT, offsetof(struct __pyx_obj_5_once_BaseDescriptor, isVolatile), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BaseDescriptor = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_BaseDescriptor = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BaseDescriptor = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BaseDescriptor = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_5_once_BaseDescriptor = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_once.BaseDescriptor", /*tp_name*/
  sizeof(struct __pyx_obj_5_once_BaseDescriptor), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5_once_BaseDescriptor, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BaseDescriptor, /*tp_as_number*/
  &__pyx_tp_as_sequence_BaseDescriptor, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BaseDescriptor, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BaseDescriptor, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "Data descriptor base class for \'Once\' bindings", /*tp_doc*/
  __pyx_tp_traverse_5_once_BaseDescriptor, /*tp_traverse*/
  __pyx_tp_clear_5_once_BaseDescriptor, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5_once_BaseDescriptor, /*tp_methods*/
  __pyx_members_5_once_BaseDescriptor, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  __pyx_tp_descr_get_5_once_BaseDescriptor, /*tp_descr_get*/
  __pyx_tp_descr_set_5_once_BaseDescriptor, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5_once_BaseDescriptor, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_once(void); /*proto*/
PyMODINIT_FUNC init_once(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_once", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_v_5_once_Py_None = Py_None; Py_INCREF(Py_None);
  if (PyType_Ready(&__pyx_type_5_once_bindingLock) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "bindingLock", (PyObject *)&__pyx_type_5_once_bindingLock) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  __pyx_ptype_5_once_bindingLock = &__pyx_type_5_once_bindingLock;
  __pyx_type_5_once_BaseDescriptor.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_5_once_BaseDescriptor) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BaseDescriptor", (PyObject *)&__pyx_type_5_once_BaseDescriptor) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  __pyx_ptype_5_once_BaseDescriptor = &__pyx_type_5_once_BaseDescriptor;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":23 */
  __pyx_v_5_once__lockType = ((void (*))((PyObject*)__pyx_ptype_5_once_bindingLock));

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":24 */
  Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_5_once_Py_None);
  __pyx_v_5_once_Py_None = Py_None;

  /* "C:\cygwin\home\pje\projects\PEAK\src/peak/binding/_once.pyx":136 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  Py_INCREF(__pyx_n_BaseDescriptor);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_BaseDescriptor);
  if (PyObject_SetAttr(__pyx_m, __pyx_n___all__, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_once");
}

static char *__pyx_filenames[] = {
  "_once.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type)) {
        if (PyErr_Warn(PyExc_DeprecationWarning,
                "raising a string exception is deprecated"))
            goto raise_error;
    }
    else if (PyType_Check(type) || PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        if (PyInstance_Check(type))
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
        else
            type = (PyObject*) type->ob_type;
        Py_INCREF(type);
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static PyObject *__Pyx_GetExcValue(void) {
    PyObject *type = 0, *value = 0, *tb = 0;
    PyObject *result = 0;
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);
    if (PyErr_Occurred())
        goto bad;
    if (!value) {
        value = Py_None;
        Py_INCREF(value);
    }
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = type;
    tstate->exc_value = value;
    tstate->exc_traceback = tb;
    result = value;
    Py_XINCREF(result);
    type = 0;
    value = 0;
    tb = 0;
bad:
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
    return result;
}

static void __Pyx_ReRaise(void) {
    PyThreadState *tstate = PyThreadState_Get();
    PyObject *type = tstate->exc_type;
    PyObject *value = tstate->exc_value;
    PyObject *tb = tstate->exc_traceback;
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    PyErr_Restore(type, value, tb);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
