/* Generated by Pyrex 0.4.6 on Fri Nov 29 16:46:03 2002 */

#include "Python.h"
#include "py_obj.h"
#include "object.h"


static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, char *name); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static char *__pyx_srcfile = "C:\\cygwin\\home\\pje\\PEAK\\src/peak/binding/data_desc.pyx";
static int __pyx_lineno;
static PyObject *__pyx_k5;


static PyObject *__pyx_f_10data_descr___set__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_10data_descr___set__ = {"__set__", (PyCFunction)__pyx_f_10data_descr___set__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_10data_descr___set__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_obj = 0;
  PyObject *__pyx_v_value = 0;
  PyObject *__pyx_v_d;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","obj","value",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_self, &__pyx_v_obj, &__pyx_v_value)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  Py_INCREF(__pyx_v_value);
  __pyx_v_d = Py_None; Py_INCREF(__pyx_v_d);

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":19 */
  __pyx_1 = GET_DICTIONARY(__pyx_v_obj); if (!__pyx_1) {__pyx_lineno = 19; goto __pyx_L1;}
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":20 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "attrName"); if (!__pyx_1) {__pyx_lineno = 20; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_v_d, __pyx_1, __pyx_v_value) < 0) {__pyx_lineno = 20; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("__set__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  Py_DECREF(__pyx_v_value);
  return __pyx_r;
}


static PyObject *__pyx_f_10data_descr___delete__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_10data_descr___delete__ = {"__delete__", (PyCFunction)__pyx_f_10data_descr___delete__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_10data_descr___delete__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_obj = 0;
  PyObject *__pyx_v_d;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","obj",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_obj)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  __pyx_v_d = Py_None; Py_INCREF(__pyx_v_d);

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":24 */
  __pyx_1 = GET_DICTIONARY(__pyx_v_obj); if (!__pyx_1) {__pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":25 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "attrName"); if (!__pyx_1) {__pyx_lineno = 25; goto __pyx_L1;}
  if (PyObject_DelItem(__pyx_v_d, __pyx_1) < 0) {__pyx_lineno = 25; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("__delete__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  return __pyx_r;
}


static PyObject *__pyx_f_10data_descr___get__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10data_descr___get__[] = "Compute the attribute value and cache it\n\n            Note: fails if attribute name not supplied or doesn\'t reference\n            this descriptor!\n        ";
static PyMethodDef __pyx_mdef_10data_descr___get__ = {"__get__", (PyCFunction)__pyx_f_10data_descr___get__, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10data_descr___get__};
static PyObject *__pyx_f_10data_descr___get__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_obj = 0;
  PyObject *__pyx_v_typ = 0;
  PyObject *__pyx_v_n;
  PyObject *__pyx_v_d;
  PyObject *__pyx_v_value;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  int __pyx_8;
  static char *__pyx_argnames[] = {"self","obj","typ",0};
  __pyx_v_typ = __pyx_k5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO|O", __pyx_argnames, &__pyx_v_self, &__pyx_v_obj, &__pyx_v_typ)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  Py_INCREF(__pyx_v_typ);
  __pyx_v_n = Py_None; Py_INCREF(__pyx_v_n);
  __pyx_v_d = Py_None; Py_INCREF(__pyx_v_d);
  __pyx_v_value = Py_None; Py_INCREF(__pyx_v_value);

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":50 */
  __pyx_1 = __Pyx_GetName(__pyx_b, "None"); if (!__pyx_1) {__pyx_lineno = 50; goto __pyx_L1;}
  __pyx_2 = __pyx_v_obj == __pyx_1;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":51 */
    Py_INCREF(__pyx_v_self);
    __pyx_r = __pyx_v_self;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":53 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "attrName"); if (!__pyx_1) {__pyx_lineno = 53; goto __pyx_L1;}
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":54 */
  __pyx_1 = GET_DICTIONARY(__pyx_v_obj); if (!__pyx_1) {__pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_v_d);
  __pyx_v_d = __pyx_1;
  __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":56 */
  __pyx_2 = PySequence_Contains(__pyx_v_d, __pyx_v_n); if (__pyx_2 < 0) {__pyx_lineno = 56; goto __pyx_L1;}
  if (__pyx_2) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":57 */
    __pyx_1 = PyObject_GetItem(__pyx_v_d, __pyx_v_n); if (!__pyx_1) {__pyx_lineno = 57; goto __pyx_L1;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":59 */
  __pyx_2 = PyObject_IsTrue(__pyx_v_n); if (__pyx_2 < 0) {__pyx_lineno = 59; goto __pyx_L1;}
  if (!(__pyx_8 = (!__pyx_2))) {
    __pyx_1 = __Pyx_GetName(__pyx_b, "getattr"); if (!__pyx_1) {__pyx_lineno = 59; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttrString(__pyx_v_obj, "__class__"); if (!__pyx_3) {__pyx_lineno = 59; goto __pyx_L1;}
    __pyx_4 = __Pyx_GetName(__pyx_b, "None"); if (!__pyx_4) {__pyx_lineno = 59; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_lineno = 59; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
    Py_INCREF(__pyx_v_n);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_n);
    PyTuple_SET_ITEM(__pyx_5, 2, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_6 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_6) {__pyx_lineno = 59; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_7 = __pyx_6 != __pyx_v_self;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_8 = __pyx_7;
  }
  if (__pyx_8) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":60 */
    __pyx_3 = PyObject_GetAttrString(__pyx_v_self, "usageError"); if (!__pyx_3) {__pyx_lineno = 60; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(0); if (!__pyx_4) {__pyx_lineno = 60; goto __pyx_L1;}
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_lineno = 60; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":62 */
  __pyx_1 = __Pyx_GetName(__pyx_m, "NOT_FOUND"); if (!__pyx_1) {__pyx_lineno = 62; goto __pyx_L1;}
  if (PyObject_SetItem(__pyx_v_d, __pyx_v_n, __pyx_1) < 0) {__pyx_lineno = 62; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":64 */
  /*try:*/ {

    /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":65 */
    __pyx_4 = PyObject_GetAttrString(__pyx_v_self, "computeValue"); if (!__pyx_4) {__pyx_lineno = 65; goto __pyx_L5;}
    __pyx_3 = PyObject_GetAttrString(__pyx_v_obj, "__dict__"); if (!__pyx_3) {__pyx_lineno = 65; goto __pyx_L5;}
    __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_lineno = 65; goto __pyx_L5;}
    Py_INCREF(__pyx_v_obj);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_obj);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
    Py_INCREF(__pyx_v_n);
    PyTuple_SET_ITEM(__pyx_5, 2, __pyx_v_n);
    __pyx_3 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_1) {__pyx_lineno = 65; goto __pyx_L5;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_1;
    __pyx_1 = 0;
  }
  goto __pyx_L6;
  __pyx_L5:;
  Py_XDECREF(__pyx_6); __pyx_6 = 0;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_5); __pyx_5 = 0;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":66 */
  /*except:*/ {
    __Pyx_AddTraceback("__get__");
    __pyx_6 = __Pyx_GetExcValue(); if (!__pyx_6) {__pyx_lineno = 66; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;

    /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":67 */
    if (PyObject_DelItem(__pyx_v_d, __pyx_v_n) < 0) {__pyx_lineno = 67; goto __pyx_L1;}

    /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":68 */
    __Pyx_ReRaise();
    {__pyx_lineno = 68; goto __pyx_L1;}
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":70 */
  __pyx_5 = __Pyx_GetName(__pyx_b, "setattr"); if (!__pyx_5) {__pyx_lineno = 70; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_lineno = 70; goto __pyx_L1;}
  Py_INCREF(__pyx_v_obj);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_obj);
  Py_INCREF(__pyx_v_n);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_n);
  Py_INCREF(__pyx_v_value);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_v_value);
  __pyx_1 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_1) {__pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":71 */
  Py_INCREF(__pyx_v_value);
  __pyx_r = __pyx_v_value;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  Py_DECREF(__pyx_v_typ);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static char (__pyx_k1[]) = "peak.api";
static char (__pyx_k2[]) = "NOT_FOUND";
static char (__pyx_k3[]) = "data_descr";
static char (__pyx_k4[]) = "Data descriptor base class for \'Once\' bindings";

DL_EXPORT(void) initdata_desc(void); /*proto*/
DL_EXPORT(void) initdata_desc(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  __pyx_m = Py_InitModule4("data_desc", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  __pyx_b = PyImport_AddModule("__builtin__");
  PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b);

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":1 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":4 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":7 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":11 */
  __pyx_1 = PyString_FromString(__pyx_k1); if (!__pyx_1) {__pyx_lineno = 11; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(__pyx_k2); if (!__pyx_2) {__pyx_lineno = 11; goto __pyx_L1;}
  __pyx_3 = PyList_New(1); if (!__pyx_3) {__pyx_lineno = 11; goto __pyx_L1;}
  PyList_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_4 = __Pyx_Import(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyObject_GetAttrString(__pyx_4, "NOT_FOUND"); if (!__pyx_5) {__pyx_lineno = 11; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "NOT_FOUND", __pyx_5) < 0) {__pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":14 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_lineno = 14; goto __pyx_L1;}
  __pyx_1 = PyString_FromString(__pyx_k3); if (!__pyx_1) {__pyx_lineno = 14; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_b, "object"); if (!__pyx_3) {__pyx_lineno = 14; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_lineno = 14; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_5 = PyString_FromString(__pyx_k4); if (!__pyx_5) {__pyx_lineno = 14; goto __pyx_L1;}
  if (PyDict_SetItemString(__pyx_2, "__doc__", __pyx_5) < 0) {__pyx_lineno = 14; goto __pyx_L1;}
  __pyx_6 = PyClass_New(__pyx_4, __pyx_2, __pyx_1); if (!__pyx_6) {__pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":18 */
  __pyx_7 = PyCFunction_New(&__pyx_mdef_10data_descr___set__, 0); if (!__pyx_7) {__pyx_lineno = 18; goto __pyx_L1;}
  __pyx_8 = PyMethod_New(__pyx_7, 0, __pyx_6); if (!__pyx_8) {__pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  if (PyObject_SetAttrString(__pyx_6, "__set__", __pyx_8) < 0) {__pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_8); __pyx_8 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":23 */
  __pyx_3 = PyCFunction_New(&__pyx_mdef_10data_descr___delete__, 0); if (!__pyx_3) {__pyx_lineno = 23; goto __pyx_L1;}
  __pyx_1 = PyMethod_New(__pyx_3, 0, __pyx_6); if (!__pyx_1) {__pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (PyObject_SetAttrString(__pyx_6, "__delete__", __pyx_1) < 0) {__pyx_lineno = 23; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/binding/data_desc.pyx":42 */
  __pyx_4 = __Pyx_GetName(__pyx_b, "None"); if (!__pyx_4) {__pyx_lineno = 42; goto __pyx_L1;}
  __pyx_k5 = __pyx_4;
  __pyx_4 = 0;
  __pyx_5 = PyCFunction_New(&__pyx_mdef_10data_descr___get__, 0); if (!__pyx_5) {__pyx_lineno = 42; goto __pyx_L1;}
  __pyx_7 = PyMethod_New(__pyx_5, 0, __pyx_6); if (!__pyx_7) {__pyx_lineno = 42; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (PyObject_SetAttrString(__pyx_6, "__get__", __pyx_7) < 0) {__pyx_lineno = 42; goto __pyx_L1;}
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  if (PyObject_SetAttrString(__pyx_m, "data_descr", __pyx_6) < 0) {__pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  __Pyx_AddTraceback("data_desc");
}

/* Runtime support code */

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
  PyObject *py_srcfile = 0;
  PyObject *py_funcname = 0;
  PyObject *py_globals = 0;
  PyObject *empty_tuple = 0;
  PyObject *empty_string = 0;
  PyCodeObject *py_code = 0;
  PyFrameObject *py_frame = 0;
  
  py_srcfile = PyString_FromString(__pyx_srcfile);
  if (!py_srcfile) goto bad;
  py_funcname = PyString_FromString(funcname);
  if (!py_funcname) goto bad;
  py_globals = PyModule_GetDict(__pyx_m);
  if (!py_globals) goto bad;
  empty_tuple = PyTuple_New(0);
  if (!empty_tuple) goto bad;
  empty_string = PyString_FromString("");
  if (!empty_string) goto bad;
  py_code = PyCode_New(
    0,            /*int argcount,*/
    0,            /*int nlocals,*/
    0,            /*int stacksize,*/
    0,            /*int flags,*/
    empty_string, /*PyObject *code,*/
    empty_tuple,  /*PyObject *consts,*/
    empty_tuple,  /*PyObject *names,*/
    empty_tuple,  /*PyObject *varnames,*/
    empty_tuple,  /*PyObject *freevars,*/
    empty_tuple,  /*PyObject *cellvars,*/
    py_srcfile,   /*PyObject *filename,*/
    py_funcname,  /*PyObject *name,*/
    __pyx_lineno,   /*int firstlineno,*/
    empty_string  /*PyObject *lnotab*/
  );
  if (!py_code) goto bad;
  py_frame = PyFrame_New(
    PyThreadState_Get(), /*PyThreadState *tstate,*/
    py_code,             /*PyCodeObject *code,*/
    py_globals,          /*PyObject *globals,*/
    0                    /*PyObject *locals*/
  );
  if (!py_frame) goto bad;
  py_frame->f_lineno = __pyx_lineno;
  PyTraceBack_Here(py_frame);
bad:
  Py_XDECREF(py_srcfile);
  Py_XDECREF(py_funcname);
  Py_XDECREF(empty_tuple);
  Py_XDECREF(empty_string);
  Py_XDECREF(py_code);
  Py_XDECREF(py_frame);
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
  PyObject *__import__ = 0;
  PyObject *empty_list = 0;
  PyObject *module = 0;
  PyObject *global_dict = 0;
  PyObject *empty_dict = 0;
  PyObject *list;
  __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
  if (!__import__)
    goto bad;
  if (from_list)
    list = from_list;
  else {
    empty_list = PyList_New(0);
    if (!empty_list)
      goto bad;
    list = empty_list;
  }
  global_dict = PyModule_GetDict(__pyx_m);
  if (!global_dict)
    goto bad;
  empty_dict = PyDict_New();
  if (!empty_dict)
    goto bad;
  module = PyObject_CallFunction(__import__, "OOOO",
    name, global_dict, empty_dict, list);
bad:
  Py_XDECREF(empty_list);
  Py_XDECREF(__import__);
  Py_XDECREF(empty_dict);
  return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, char *name) {
  PyObject *result;
  result = PyObject_GetAttrString(dict, name);
  if (!result)
    PyErr_SetString(PyExc_NameError, name);
  return result;
}

static PyObject *__Pyx_GetExcValue(void) {
  PyObject *type = 0, *value = 0, *tb = 0;
  PyObject *result = 0;
  PyThreadState *tstate = PyThreadState_Get();
  PyErr_Fetch(&type, &value, &tb);
  PyErr_NormalizeException(&type, &value, &tb);
  if (PyErr_Occurred())
    goto bad;
  if (!value) {
    value = Py_None;
    Py_INCREF(value);
  }
  Py_XDECREF(tstate->exc_type);
  Py_XDECREF(tstate->exc_value);
  Py_XDECREF(tstate->exc_traceback);
  tstate->exc_type = type;
  tstate->exc_value = value;
  tstate->exc_traceback = tb;
  result = value;
  Py_XINCREF(result);
  type = 0;
  value = 0;
  tb = 0;
bad:
  Py_XDECREF(type);
  Py_XDECREF(value);
  Py_XDECREF(tb);
  return result;
}

static void __Pyx_ReRaise(void) {
  PyThreadState *tstate = PyThreadState_Get();
  PyObject *type = tstate->exc_type;
  PyObject *value = tstate->exc_value;
  PyObject *tb = tstate->exc_traceback;
  Py_XINCREF(type);
  Py_XINCREF(value);
  Py_XINCREF(tb);
  PyErr_Restore(type, value, tb);
}
